server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: ${application.settings.general.info.application-name}
  main:
    banner-mode: "off"

application:
  settings:
    general:
      spring:
        profile: ${spring.profiles.active}
      info:
        application-version: '@project.version@'
        application-name: sidequest-app